# 다음을 테마로 적용해 본다 - 1. 
#
#[theme]
#primaryColor="#00ff00"
#backgroundColor="pink"
#secondaryBackgroundColor="aqua"
#textColor="red"
#font="serif"

# 다음을 테마로 적용해 본다 - 2. 
#
#[theme]
#primaryColor="red"
#backgroundColor="#6EC531"
#secondaryBackgroundColor="#F1D651"
#textColor="#856256"
#font="sans serif"

# 다음을 테마로 적용해 본다 - 3. 
#
[theme]
base="dark" #  또는  "light"

# HEX 컬러는 다음 사이트를 참고해 본다.
# https://www.color-name.com/